# automate game ----

automate_game <- function(suggested_guess,
                          answer = generate_word(),
                          pre_calc = FALSE,
                          guess_data,
                          print = TRUE
                          ){
  
  # start with whatever suggested guess you like
  # pre-calc will expect a df of guess_data
  # which is generated by get_two_step_e_bits() for your starting word
  
  df <- mystery_words
  
  if(print) {
    message("Running a new game!")
  }
  
  for(turn in (1:100)){ # run for 100 turns - can define anything over 6 as failure later
    
    # set guess
    guess <- suggested_guess
    
    if (print) {
      message("----------------------------------------------")
      message(paste0("Turn ", turn, " | Suggested guess: '", suggested_guess, "'"))
      
    }
    
    # run game and find new words
    results <- get_guess_answer_results(guess,answer)
    output_guess_with_colours(guess,results)
    
    # Check win
    if(results == "ppppp"){
      turns <- turn
      break()
    }
    
    # filter to remaining words
    df <- filter_mystery_words(df,guess,results)
    
    # If no win, look at next possible guesses
    if(print) {
      message(paste0(" There are ", nrow(df), " possible words remaining:"))
      df %>% select(word) %>% pull() %>% print()
    }
    
    
    # find next word
    # for the first round we can use pre-calc if available
    if (pre_calc & turn == 1) {
      suggested_guess <-
        guess_data %>%
        filter(results_1 == results) %>%
        pull(guess_2)
      
    # otherwise do it live
    } else {
      suggested_guess <-
        get_best_next_guess(guess, results, input_df = df,print = FALSE) %>% 
        pull(guess_2)
    }
  }
  # return here
  if(print){
    message(paste0("Successfully found '",guess,"' in ",turns," turns!"))
  }
  return(turns)
}

simulate_game <- function(guess, sims, all_answers = TRUE){
  
  # get_guess_data
  
  pre_calc_data <- 
    read_rds(paste0("data/two_step_results/two_step_",guess,".rds"))
  
  # run game with precalcs
  simulation_results <- tibble()
  
  # doing this for every answer?
  if(all_answers){
    sims <- nrow(mystery_words)
  }
  
  for(i in 1:sims){
    
    if(all_answers){
      pre_gen_answer <- mystery_words$word[i]
    } else {
      pre_gen_answer <- generate_word()
    }
    # get the number of turns it took
    turns <- 
      automate_game(guess,
                    answer = pre_gen_answer,
                    pre_calc = TRUE,
                    guess_data = pre_calc_data,
                    print = FALSE)
    
    # add to table
    simulation_results <- 
      bind_rows(
        simulation_results,
        tibble(
          simulation = i,
          answer = pre_gen_answer,
          first_guess = guess,
          turns = turns
          )
        )
    # output results
    
  }
  simulation_results %>% return()
}


simulate_best_words <- function(words = 2){
  
  # check words you already have
  existing_results <- 
    tibble(files = list.files("data/simulation_results/")) %>% 
    # slightly clumsy but whatever
    mutate(word = str_sub(files,1,5)) %>% 
    pull(word)
  
  # get the best ebit words you know about
  top_words <- 
    map_dfr(
      list.files("data/two_step_results/",full.names = TRUE),
      ~read_rds(.x)
    ) %>% 
    group_by(guess_1) %>% 
    mutate(p_1 = results_1_appear/sum(results_1_appear)) %>% 
    mutate(bits_1 = log2(1/p_1)) %>% 
    mutate(bits = bits_1 + e_bits_2) %>% 
    summarise(e_bits = sum(p_1*bits)) %>% 
    # take the best words
    slice_max(e_bits, n = words) %>% 
    # don't worry about stuff thats done already
    filter(!guess_1 %in% existing_results) %>% 
    pull(guess_1)
  
  # run simulations on all of these and save results
  for(word in top_words){
    simulate_game(word,all_answers = TRUE) %>% 
      write_rds(paste0("data/simulation_results/",word,"_simulations.rds"))
  }
}


# chart sim results -------------------------------------------------------



chart_results <- function(){
  
  # get all our sim data
  result_data <- 
    map_dfr(
      list.files("data/simulation_results/",full.names = TRUE),
      ~read_rds(.x))
  
  result_data %>% 
    group_by(first_guess,turns) %>% 
    summarise(count = n(),
              .groups = "drop") %>% 
    group_by(first_guess) %>%
    mutate(count_prop = count/sum(count)) %>% 
    mutate(mean = sum(turns*count_prop)) %>% 
    mutate(guess_label = paste0(
      str_to_title(first_guess),
      " (",
      round(mean, 3),
      ")"
    )) %>% 
    
    ggplot(aes(x = factor(turns),
               y = count_prop)) + 
    geom_col(aes(fill = factor(turns)),
             width = 1) + 
    
    geom_text(aes(label = count),
              vjust = - 1) +
    
    scale_y_continuous(limits = c(0,1),
                       n.breaks = 10) +
    
    labs(x = "Turns Taken") +
    scale_fill_viridis(discrete = TRUE, direction = -1,
                       begin = 0.3,
                       end = 1) + 
    # theme_minimal() +
    theme_classic() +
    # theme_bw() +
    theme(
          # axis.line.y = element_blank(),
          # axis.ticks = element_blank(),
          # axis.text.y = element_blank(),
          axis.title.y = element_blank(),
          panel.grid = element_blank(),
          legend.position = "none",
          strip.text = element_text(size = 12, face = "bold")
    ) +
    
    facet_wrap( ~ reorder(guess_label,mean), scales = "free_y")
  
}


 
